server:
  port: ${SERVER_PORT:8080}

spring:
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:create-drop}
      show-sql: true
  datasource:
    platform: postgres
    url: ${POSTGRES_URL:jdbc:postgresql://ec2-52-49-120-150.eu-west-1.compute.amazonaws.com:5432/d409ucrvidf06t}
    username: ${POSTGRES_USERNAME:scxqtmotsknxdn}
    password: ${POSTGRES_PASSWORD:ecc742bfcb88ca6048e7f9baa8c12be9caaabe7362a8e049252742c4c65002eb}
    driverClassName: org.postgresql.Driver